let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`"${pickRandom(global.amor)}”`, m)
}
handler.help = ['bucin']
handler.tags = ['quotes']
handler.command = /^(bucin)$/i
handler.premium = true
module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

// https://jalantikus,com/tips/kata-kata-bucin/
global,amor = [
"Besa despacio, olvida rápido, toma riesgos y nunca, nunca te arrepientas...",
"Fue la forma en la que sonreíste,,, supe que siempre querría eso en mi vida.",
"Enamorarse es una sensación maravillosamente terrorífica.",
"Fue la forma en la que sonreíste,,, super que siempre querría eso en mi vida.",
"Amarse es comprender que somos dos seres individuales pero que decidieron compartir una vida juntos.",
"Anoche miré al cielo y empecé a dar a cada estrella una razón por la que te quiero tanto, Me faltaron estrellas.",
"Desearía poder hablarte, desearía poder sonreírte, desearía poder abrazarte, pero sobre todo desearía poder besarte.",
"Tus imperfecciones te convierten en la mujer perfecta.",
"Entrégame el tiempo que te sobre, y lo gastaré en hacerte la persona más feliz del planeta.",
"Te adoro como si fueses una Santa de mi religión, como si siguiese mi camino al son de tu corazón.",
"He escrito novelas románticas sobre papel, pero en mi corazón se encuentra mi amor por ti, el más fiel.",
"Un suspiro es el aire que nos sobra por alguien que nos falta.",
"El amor consta de un alma presente en dos cuerpos, y de un corazón que reside en dos almas.",
"Vivamos y que pase lo que tenga que pasar.",
"Si mi amor por ti fuera una flor, podría caminar en este jardín por siempre.",
"Estuviste ahí cuando más te necesitaba,,, y también cuando creía que no, Gracias por todo, amor.",
"No cambiaría un minuto de ayer contigo por cien años de vida sin ti.",
"Seré un ladrón de minutos para estar más tiempo a tu lado.",
"Unos ojos que jamás me cansaré de mirar, unos labios que siempre querré besar, pero lo mejor de todo, un corazón que jamás dejaré de amar.",
"Solo entendí qué era el amor cuando llegaste a mi vida y le diste sentido.",
"Si algún día no puedo mirarte, para mí será un día oscuro, porque tú eres mi único sol, el que me ilumina, amor mío.",
"Me cuesta pensar que has estado ahí siempre,,, y que he tardado tanto en encontrarte, amor.",
"Del cielo bajó un pintor para pintar tu figura, pero no encontró color para tanta hermosura.",
"Nada me parece más bello que observar el mundo a través de tus ojos.",
"Eres un lindo paisaje con el que me quiero deleitar, tus ojos las flores, tu rostro la pradera y tu boca el mar.",
"Nunca antes se había visto un amor igual al que siento por ti; no cabe en mi corazón, ni tampoco en este universo.",
"Cuenta la leyenda que desde tu cama se puede viajar a lo más alto del cielo.",
"El destino de nuestros labios es encontrarse, ¿para qué alargarlo más?",
"Un náufrago feliz sería, si tu boca fuese el mar y yo un marinero a la deriva.",
"Dios se endeudó conmigo, y por eso me trajo a ti.",
"Te amo en colores que aún no has visto.",
"Te amo en formas que jamás podrías adivinar...",
"Anoche pedí a un ángel que fuese a protegerte mientras dormías, Al rato volvió y le pregunté por qué había vuelto, Un ángel no necesita que otro lo proteja, me respondió.",
"Lo más bonito es que no eres consciente de lo bella que eres, y es esa inocencia lo que más me enamora de ti.",
"Cuando nos presentaron, cogí una aguja y la solté en medio del mar, y cuando alguien la encuentre no te volveré a amar.",
"La luz no existe si no me alumbras con tu presencia.",
"No me importa que pasen las horas, los días y los años; lo único que deseo es que todo ese tiempo que pase sea a tu lado, princesa.",
"Tú eres la estrella de mi universo.",
"Te amo como el agua de los océanos, en ocasiones calmado, en ocasiones con intensidad.",
"Agua hay en los mares y los océanos, pero de fuego es el amor que yo te quiero entregar.",
"El día más oscuro será aquel en que no pueda encontrarte, amor.",
"Quiero que la distancia entre nosotros sea tan corta que nos obligue a besarnos.",
"No puede arreglarte la misma persona que te rompió.",
"Algunos de tus silencios rompen la barrera del sonido.",
"Temo despertarme una mañana y que ya no estés al otro lado de la cama.",
"Hay muchas mujeres preciosas en este mundo, pero yo solo te amo a ti.",
"Si pudiese despertarme todas las mañanas mirándote y oliéndote, mi vida sería perfecta.",
"Mis ojos nunca supieron guardarme todo el amor que siento por ti.",
"Somos una casualidad llena de intención.",
"Cuando miro las estrellas, su luz me recuerda las ganas que tengo de recorrer con mis labios cada centímetro de tu piel.",
"Déjame dejarte ir u oblígame a no soltarte nunca más.",
"Eres mi combustible, la fuente de energía que mantiene viva la llama de mi ilusión.",
"Te amo hoy más que ayer, pero no más de lo que te amaré mañana.",
"Sería un privilegio que alguien como tú me robara el corazón... ",
"Dueñas son las flores de las praderas, las nubes del cielo, pero tú, cariño mío, eres dueña de mis sentimientos.",
"Si tras la muerte no he sido capaz de confesar lo que siento por ti, en mi lápida escribiré sobre el amor que habita dentro de mí.",
"Atravesar un oscuro sendero no me importaría, si me encontrase con tu luz al final de la partida.",
"Inmerso en la soledad con tu mirada me crucé, y desde entonces lleno de amor me encontré.",
"Un tulipán sin agua vive pocos días, pero tu amor y el mío, si se unen, durarán toda la vida.",
"Hoy he comprobado que la luna no brilla tanto como tu rostro, por eso vivo tan enamorado.",
"El agua fluye por el río hacia el mar, y yo fluyo para que tu corazón me deje entrar.",
"Si tú fueras horizonte y yo el sol, esperaría el atardecer cada día para poder unirnos los dos.",
"Muchas veces el corazón ve lo que es invisible para el ojo.",
"A veces las cosas se van y nunca más vuelven,,,, espero que esa no seas nunca tú.",
"Te escribo un poema a cambio de tu amor, Soy consciente de que no es justo, pero es lo mejor que puedo ofrecerte.",
"Cuando sueño contigo, el tiempo pasa volando,,, pero ya estoy acostumbrado porque me paso el día pensando en ti.",
"Tu mirada delata nuestra bonita historia de amor, tus besos apasionados revelan nuestro romance desenfrenado.",
"Nunca había creído que la vida pudiese ser tan bella, hasta que tú apareciste y empezaste a formar parte de ella.",
"Como el mar sin agua, como un bosque sin árboles, así me siento por dentro los días que no puedo hablar contigo.",
"Tu boca es como una copa vacía que quiero llenar con mi mejor cóctel, la pasión.",
"Uno aprende a amar no cuenta encuentra a la persona perfecta, sino cuando aprende a creer en la perfección de una persona imperfecta.",
"Te quiero no solo por cómo eres, sino por cómo soy yo cuando estoy contigo.",
"Tu mano tocando la mía,,, así es como chocan las galaxias.",
"El amor sucede accidentalmente, en un momento, en un solo instante.",
"Si eres capaz de explicar qué es el amor, es que nunca has estado enamorado.",
"El amor no consiste solamente en mirarse el uno al otro, sino en mirar juntos en la misma dirección.",
"Si no cambias, todo se repite.",
"Dejé de buscar cuál era el significado de la vida en cuanto vi tu sonrisa.",
"Eres la razón por la que no hay nadie más en mi vida, Eres la razón por la que nunca habrá nadie más.",
"Fingir que no duele duele el doble...",
"Aunque ahora haya terminado, nunca olvidaré todo lo que has hecho por mí.",
"Nada ocurre sin dejar huella,,, y tú dejaste la más grande en mi alma.",
"Intentaré sonreír por lo sucedido, no llorar porque haya terminado.",
"A veces las cosas deben romperse para volver a unirse más fuertes que nunca... ",
"Te amo por tu forma de ser, no por como tú dices ser.",
"Saborear tus labios poco a poco para derretirme con tus besos como un tonto.",
"Antes, mi dilema era que nunca había visto la perfección, pero el día que te vi encontré la solución.",
"La vida es demasiado corta para pasármela haciendo ver que no me muero por ti...",
"El tiempo que nos quede, sea el que sea, quiero pasarlo a tu lado.",
"Esos tiernos labios tienen que deleitar con cada beso que das, ¿Puedo probar? ",
"Me apeteces tanto que pasaré de indirectas y sutilezas.",
"La cosa era perdernos, no perderte.",
"Ni el fuego me quema tanto como tus ojos me arden en el alma.",
"Si te preguntan que fuimos, diles que fuimos las ganas de serlo todo, pero al final no fuimos nada.",
"Aunque la sonrisa es mía, tú eres la razón por la cual sonrío.",
"Sobre el amor es imposible mentir.",
"Si no lo confiesa tu boca, ya lo hará tu corazón o tu respiración.",
"Si el amor no está lleno de un poco de locura, no es amor...",
"Muchos en este mundo te considerarán una persona más, pero para mí eres lo más importante de este mundo, eres mi mundo.",
"Si despertase cada mañana con un beso tuyo, no necesitaría nada más para ser feliz.",
"Queríamos ser tanto que se nos olvidó ser algo...",
"Tu amor,,, ese es el latido más largo de mi corazón.",
"Si realmente quieres a alguien, díselo.",
"El único invitado a mi fiesta eres tú.",
"Te quiero más que los peces al agua.",
"Lo único que siempre he querido ha sido verte sonreír.",
"¿Que cuál es mi libro preferido? El que estoy escribiendo con todas nuestras conversaciones.",
"Fíjate qué cosas, que me topé a la vez con el amor y contigo.",
"Me haces engordar con tanta dulzura.",
"Te pareces un montón a mi nuevo novio.",
"O aportas o apartas, pero no puedes hacer ambos, cariño.",
"Nadie me hace tan feliz como tú.",
"Me basta con mirarte para hacerme invencible.",
"Gracias por existir, amor.",
"Quién fuera cantautor para escribirte una canción, pero como no lo soy, te dedico todo mi corazón.",
"Nuestro amor es un récord, es infinitamente perfecto.",
"¿Qué se siente al ser la dama más bella de la galaxia?",
"Quién fuera tu canción favorita para pasarse el día en tus pensamientos.",
"Hay quien desea comerse el mundo, otros desean el poder sobre el pueblo, pero yo solamente deseo hacerme un huequito en tu corazón.",
"Quisiera que me besaras hasta dejarme sin aliento, Perder el conocimiento, tocar el cielo contigo... ",
"Al final, mi historia de amor solo valdrá la pena si tú eres el protagonista. ",
"Los que más critican son los que menos saben de amor, cariño,,, deja que hablen. ",
"Esa cosa que crees que es tu defecto - es el motivo por el que me estoy enamorando de ti.",
"Enamorarse de los pensamientos de alguien; el romance más íntimo y espléndido.",  
"El amor es la causa de la diversidad en nuestro planeta, Además de un sentimiento, les la semilla de todo lo que se ha creado.",
"Lo que tenemos es demasiado bello para metáforas, cariño.",
"El amor verdadero no surge cuando nos encontramos a alguien perfecto, sino cuando vemos la perfección en alguien imperfecto.",
"No esperes el momento perfecto para actuar, escoge cualquier momento y conviértelo en perfecto.",
"Tu belleza y tu ternura nubla la gravedad de mis problemas,,, gracias por todo.",
"Entregaría mi vida por una gota de tu dulzura, regalaría mi alma por poder amarte una sola noche.",
"El amor es como los incendios, es más fácil ver el humo desde fuera que si te estás quemando dentro.",
"Desearía morir si para verte tuviese que pagar con mi vida.",
"Me hundiría si tus labios fuesen el mar, para así en tu boca poderme ahogar.",
"En realidad nunca nos enamoramos de una persona, sino de la imagen que nos hacemos en nuestra cabeza de esa persona.",
"Dicen que no hay hombre bueno, pero creo que contigo descubrí la excepción.",
"Algunos hombres nacen para amar únicamente a una mujer, Y qué pena, porque es muy complicado toparse con ella.",
"El amor se basa en la casualidad, por lo tanto ten el corazón abierto, porque cuando menos te lo esperes aparecerá tu media naranja.",
"Depura tu corazón antes de volver a enamorarte, ya que incluso la historia más bonita se enturbia con un pasado sucio.",
"Quién fuera tu cerebro para indagar en tus pensamientos, y descubrir si sientes por mí lo que yo por ti siento.",
"Hace 25 años una estrella a la tierra cayó, ¡Feliz cumpleaños, mi amor!",
"No hay vida más bella que la que pueda pasar a tu lado.",
"Si tu corazón fuera una prisión y mi amor por ti una cadena, no sabes lo feliz que me haría cumplir mi condena.",
"Puede que la apariencia externa capte tu interés, pero solamente su interior llenará tu corazón.",
"Nada se compara a lo que siento al estar contigo.",
"Pasaría tres vidas buscándote, pero aún así no me rendiría.",
"Vivir contigo es mi más plena felicidad,,, gracias por compartir tus días a mi lado.",
"Por dejarme ser parte de tus victorias y por dejarme estar a tu lado en cada fracaso... gracias, amor.",
"Mi confianza en ti es plena, vida mía, sé que puedes llegar a lo que te propongas.",
"Si no recuerdas la locura en la que el amor te hizo caer, no has amado.",
"El amor más fuerte es aquel que puede demostrar fragilidad.",
"Es mejor haber amado y perdido que jamás haber amado.",
"Deja un espacio en tu corazón para vivir la historia de amor más bella de toda tu vida.",
"Te amo más que a mi propia piel.",
"Me cruzaré con experiencias fantásticas y con momentos maravilloso, pero por muy buenos que sean, en mi cabeza tendré tus ojos.",
"Quién fuera piloto para volar contigo, pero puedes subirte a mi corazón y te haré sentir vértigo.",
"El lápiz se puede borrar, una torre se puede derrumbar, pero no existe amor verdadero que a un hombre y una mujer pueda separar.",
"Cariño mío, espero que nunca me olvides, porque si no me estarás matando.",
"No necesito a un príncipe teniéndote a ti a mi lado.",
"Nunca he disfrutado de los silencios, pero es que contigo son una melodía para mis oídos.",
"Sonidos raros, miradas, sonrisas, besos y abrazos, Así hablamos tú y yo.",
"Eres mi príncipe azul, al igual que yo tu princesa, dejemos que esta bonita historia quede grabada para la posteridad.",
"Mi corazón llora por amarte, mis manos por acariciarte, mi boca por besarte.",
"¿El día más feliz de mi vida? El día que te dije sí quiero.",
"Sí quiero, Sí quiero hoy, mañana y todos los días de mi vida.",
"Nada me llena más que la certeza de poder pasar una vida a tu lado... gracias por tanto, amor.",
"Mi hogar son tus brazos.",
"No me importa cuáles sean tus planes... mientras me incluyas en ellos.",
"¿Qué más da dónde vayamos? ¿Qué importa lo que nos depare el futuro? A tu lado sé que todo es posible, amor.",
"Sean cuáles sean tus metas, estaré a tu lado siempre para apoyarte y agradecerte la confianza.",
"El matrimonio no es fácil; tienes que hacer sacrificios y tomar riesgos constantemente, Pero cuando miras a esa persona especial, todo vale la pena.",
"Nada me hace más feliz que ser tu esposa y saber que cuentas conmigo para todo.",
"No hay monte demasiado alto para nuestros sueños, amor.",
"Amor, el mejor consuelo de todos es estar entre tus brazos.",
"Lo mejor de soñar contigo es que el sueño no termina cuando me despierto.",
"Ese día en que las piedras cobren vida y el sol deje de salir al amanecer, ese día no te volveré a amar",
"Amor, no hay universo que pueda eclipsar tantísima belleza.",
"Sé que voy a quererte sin preguntas, sé que vas a quererme sin respuestas.",
"El amor es un misterio, Todo en él son fenómenos, a cual más inexplicable, En el amor todo es vaguedad, absurdo e ilógico.",
"Gustavo Adolfo Bécquer.",
"¿Qué sabrán ellos de todo el amor que nos rodea?.",
"El amor, corazón, no se mide,,, el amor es un arte.",
"Al final, es así de sencillo: no me importa nada si puedo estar contigo.",
"Te amo por lo que eres, no por lo que ven los demás.",
"Una larga carrera como jardinero y justo hoy me encuentro con la rosa más hermosa que jamás había visto.",
"Era un día soleado cuando tu mirada me cautivó, tu alma atrapó mi corazón y fue entonces cuando supe lo que era el amor.",
"Cada vez que me besas, por dentro me recorre una voz: es lo mejor que me ha pasado en la vida.",
"No soy arquitecto, pero gracias a ti he construido un rascacielos de felicidad.",
"Con tu sonrisa me basta, ya que verte sonreír es lo que me motiva todos los días.",
"Te dedico mi vida, es lo que menos que puedo hacer cuando tú me entregaste tu amor.",
"Qué pesado soy, pero no puedo evitar dedicarte un *Te amo* día tras día, lleno de alegría.",
"Esto que tengo contigo, que no sé exactamente qué es, no seré capaz de tenerlo nunca con nadie más.",
"Quiero decirte mil cosas, pero ni una vida será suficiente para expresarlas todas.",
"Sabes mejor que nadie que lo nuestro no ha sido fácil,,, pero mirándote hoy a los ojos, sé que cada paso ha valido la pena.",
"Que sean felices los que nos intentaron separar, que a tu lado yo sé que tengo todo lo que necesito.",
"Nadie nunca ha sabido llenarme tanto con tan poco.",
"Me perdí en tu mirada, y a veces siento que todos estos años después... aún no he logrado encontrarme.",
"Gracias por tanta dulzura, por el amor y el cariño que me has dado sin esperar nada a cambio, Te debo la vida, amor.",
"Que bonita es la vida a tu lado,,, daría lo que fuera para no cambiar nunca cómo estamos.",
"Eres mi princesa y siempre lo serás; que los miedos no te impidan conocer esa verdad.",
" Una sonrisa de tus labios lo puede todo,,, a todo renunciaría para verte feliz.",
"Ni en cien años conseguiría compartir contigo todo lo que me haces sentir... pero moriré intentándolo encantado.",
"Tu dulzura, mi cariño y nuestro amor para siempre, ¿Qué te parece? ",
"Lo único que necesito para ser verdaderamente feliz es tenerte a mi lado y saber que me eliges.",
"No es que seas mi primera opción, cariño, es que a tu lado no hay ninguna otra.",
"Ni siquiera el tiempo podrá romper todo lo que tenemos.",
"Nada duele tanto como querer abrazarte y no poder llegar a ti... pero tengo esperanza y soy *paciente, por ti haré lo que haga falta.",
"La tristeza de necesitarte y no poder tenerte me llena cada día más... pero la esperanza de *saber que volverá a abrazarte me mantiene en pie.",
"Eres esa persona que tiene el privilegio de hacerme sonreír con tan solo escribirme.",
"Cuando alguien lo es todo, la distancia no significa nada.",
"Si pudiera teletransportarme iría directo hacia donde tú estás... no lo dudes ni un instante.",
"Te esperaré, Cueste lo que cueste, pase lo que pase, No lo dudes nunca.",
"Mi lugar favorito en el mundo es estar a tu lado,,, pronto podremos quedarnos ahí para siempre.",
"Los valles, las montañas y las carreteras no podrán romper jamás lo nuestro.",
"Cuando te mate nuestra distancia, recuerda que el sol y la luna tampoco pueden estar juntos... pero no por eso dejan de intentarlo.",
"Te quiero, amor, más de lo que podría expresa con palabras, Que la distancia no te haga dudar, que mi amor prevalga siempre por encima.",
"Te echo tanto de menos que me rompo por dentro al escuchar tu voz.",
"Al menos me acostaré sabiendo que podemos dormir bajo la misma luna... cuando la mires, piensa en mí, Tú estarás presente en cada uno de mis recuerdos",
"It's you, it's me, it's us, Always, (Eres tú, soy yo, somos nosotros... siempre)",
"If I had to start a new life, I'd want to meet you all over again, (Si tuviera que empezar una nueva vida, querría estar contigo otra vez)",
"Being deeply loved by someone gives you strenght, (Ser profundamente amado por alguien te da fuerzas)",
"What would I be without you,,,? I don't want to know, (¿Qué sería yo sin ti? No lo quiero saber)",
"If there's love, there's life, (Si hay amor, hay vida)",
"I love you for what you are, but most of all I love you for what you make me feel, (Te quiero por lo que eres, pero sobre todo te quiero por lo que me haces sentir)",
"Do you believe in love at first sight or should I walk by again? (¿Crees en el amor a primera vista o tengo que volver a pasar?)",
"f I had a flower everytime I thought of you, I could walk in a garden forever, (Si tuviera una flor cada vez que pienso en ti, podría caminar en un jardín para siempre)",
"When I saw you, I fell in love,,, and you smiled because you knew, (Cuando te vi, me enamoré,,, y tu sonreíste porque lo supiste)",
"We don't remember days, we remember moments, (No recordamos días, recordamos momentos)",
"You're the only one for me, (Eres el único para mí)",
"I've been on cloud nine since I met you, (He estado en el séptimo cielo desde que te conocí)",
"Love doesn't cure the pain but sometimes it makes it bearable, (El amor no cura el dolor pero, a veces, hace que sea soportable)",
"The further you are, the closer I feel you, (Cuanto más lejos estás, más cerca te siento)",
"I'd rather spend the rest of my life missing you than being with someone else, (Preferiría pasar el resto de mi vida echándote de menos que estar con otra persona)",
"I was a chapter in your story but you were my entire book, (Yo fui un capítulo de tu historia pero tu fuiste mi libro entero)",
"Don't you know that rules were made to be broken? (¿A caso no sabes que las reglas se hicieron para romperse?)",
"I love you because your happiness is essential for my own, (Te amo porque tu felicidad es esencial para la mía)",
"Love is like the wind; you can't see it but you can feel it, (El amor es como el viento, no puedes verlo pero puedes sentirlo)",
"Nothing is impossible when it comes to dreams and love, (Nada es imposible si se trata de los sueños y del amor)",
"Love isn't about asking all the questions, it's about giving all the answers, (El amor no va de preguntarlo todo, sino de dar todas las respuestas)",
"To love means to be vulnerable, (Amar significa ser vulnerable)",
"love you because the entire universe conspired to help me find you, (Te amo porque el universo entero conspiró para ayudarme a encontrarte)",
"Your eyes make me feel like I'm the richest person on earth, (Tus ojos me hacen sentir como la persona más rica de la Tierra)",
"You only live once, but if you're with me, once is more than enough, (Solo vives una vez, pero si estás a mi lado, una vez es más que suficiente)",
"I will go anywhere, as long as you're next to me, (Iré a cualquier parte, mientras estés a mi lado)",
" It doesn't matter how much time we spend together; I fall in love with you everyday, (No importa el tiempo que pasemos juntos; yo me enamoro de ti cada día)",
"To love another person is to see the face of God, (Amar a alguien es ver el rostro de Dios)",
"Love is so short, forgetting is so long, (Es tan corto el amor y tan largo el olvido)",
"I haven't had one bad day since I met you, And if I have, you have made it better, (No he tenido un mal día desde que te conozco, Y si lo he tenido, tú lo has mejorado)",
"I used to think soulmates didn't exist,,, but then I met you, (Solía pensar que no existían las almas gemelas,,, pero después te conocí)",
"Love happens accidentally, in a heartbeat, in a single flashing, (El amor sucede accidentalmente, en un momento, en un solo instante)",
"I learn more about myself being next to you, and that's love, (Aprendo más de mí estando a tu lado y eso es amor)",
"Ningún amor tarda tanto en llegar como aquel que nunca se empieza.",
"Más de 7 billones de sonrisas,,, pero la tuya es mi favorita.",
"Nunca es tarde para amarme, Mi respuesta es otra cosa.",
"A ti no te hace perfecta tu cuerpo, te hace perfecta tu mente.",
"Si alguien no se queda, nunca valió la pena en primer lugar.",
"A veces la vida te sorprende con una bonita coincidencia.",
"Se me antojan un par de besos tuyos...",
"Te amaré siempre, aunque no lo sepas, El silencio será mi cómplice.",
"La ironía es que el pasado siempre esté tan presente.",
"El amor es la única locura por la que no te encierran.",
"Todos mis versos hablan de ti.",
"Te conozco de siempre pero llegaste hace solo un rato.",
"Imposible solo es una palabra con un par de letras de más.",
"Si pudieras entrar en mi cabeza, verías que mis pensamientos están empapados de tu esencia.",
"Eres el sueño más bonito que nunca he tenido, porque me niego a pensar que alguien como tú puede ser real.",
"Cuando el amor es real, encuentra el camino de vuelta.",
"No quiero parar de crear recuerdos contigo.",
"Sería pecado estar a tu lado y no intentar besar tus labios.",
"Te amo con tanta profundidad que el océano debería estar celoso.",
"Estás escondido en cada uno de mis poemas...",
"Ojalá me robaras un beso y me pidieras de rescate un millón más.",
"A tu lado, amor, la vida es una fiesta.",
"Nunca acabaré de enamorarme de ti.",
"Todas las historias de amor son hermosas, pero la nuestra es mi favorita.",

]
