let handler = async (m, { conn, command, text }) => {
    conn.reply(m.chat, `
*El IQ de:* ${text}
*Es de:* ${pickRandom(["1 Es retrasado",
"2 Es retrasado",
"3 Es retrasado",
"4 Es retrasado",
"5 Es retrasado",
"6 Es retrasado",
"7 Es retrasado",
"8 Es retrasado",
"9 Es retrasado",
"10 Es retrasado",
"11 Es retrasado",
"12 Es retrasado",
"13 Es retrasado",
"14 Es retrasado",
"15 Es retrasado",
"16 Es retrasado",
"17 Es retrasado",
"18 Es retrasado",
"19 Es retrasado",
"20 Es retrasado",
"21 Es retrasado",
"22 Es retrasado",
"23 Es retrasado",
"24 Es retrasado",
"25 Es retrasado",
"26 Es retrasado",
"27 Es retrasado",
"28 Es retrasado",
"29 Es retrasado",
"30 Es retrasado",
"31 Es retrasado",
"32 Es retrasado",
"33 Es retrasado",
"34 Es retrasado",
"35 Es retrasado",
"36 Es retrasado",
"37 Es retrasado",
"38 Es retrasado",
"39 Es retrasado",
"40 Es retrasado",
"41 Es retrasado",
"42 Es retrasado",
"43 Es retrasado",
"44 Es retrasado",
"45 Es retrasado",
"46 Es retrasado",
"47 Es retrasado",
"48 Es retrasado",
"49 Es retrasado",
"50 Es retrasado",
"51 Es retrasado",
"52 Es retrasado",
"53 Es retrasado",
"54 Es retrasado",
"55 Es medio retrasado",
"56 Es medio retrasado",
"57 Es medio retrasado",
"58 Es medio retrasado",
"59 Es medio retrasado",
"60 Es medio retrasado",
"61 Es medio retrasado",
"62 Es medio retrasado",
"63 Es medio retrasado",
"64 Es medio retrasado",
"65 Es medio retrasado",
"66 Es medio retrasado",
"67 Es medio retrasado",
"68 Es medio retrasado",
"69 Es medio retrasado",
"70 Es tonto",
"71 Es tonto",
"72 Es tonto",
"73 Es tonto",
"74 Es tonto",
"75 Es tonto",
"76 Es tonto",
"77 Es tonto",
"78 Es tonto",
"79 Es tonto",
"80 Es casi tonto",
"81 Es casi tonto",
"82 Es casi tonto",
"83 Es casi tonto",
"84 Es casi tonto",
"85 Es casi tonto",
"86 Es casi tonto",
"87 Es casi tonto",
"88 Es casi tonto",
"89 Es casi tonto",
"90 Es promedio",
"91 Es promedio",
"92 Es promedio",
"93 Es promedio",
"94 Es promedio",
"95 Es promedio",
"96 Es promedio",
"97 Es promedio",
"98 Es promedio",
"99 Es promedio",
"100 Es promedio",
"101 Es promedio",
"102 Es promedio",
"103 Es promedio",
"104 Es promedio",
"105 Es promedio",
"106 Es promedio",
"107 Es promedio",
"108 Es promedio",
"109 Es promedio",
"110 Esta arriba del promedio",
"111 Esta arriba del promedio",
"112 Esta arriba del promedio",
"113 Esta arriba del promedio",
"114 Esta arriba del promedio",
"115 Esta arriba del promedio",
"116 Esta arriba del promedio",
"117 Esta arriba del promedio",
"118 Esta arriba del promedio",
"119 Esta arriba del promedio",
"120 Es superior",
"121 Es superior",
"122 Es superior",
"123 Es superior",
"124 Es superior",
"125 Es superior",
"126 Es superior",
"127 Es superior",
"128 Es superior",
"129 Es superior",
"130 Es muy superior",
"131 Es muy superior",
"132 Es muy superior",
"133 Es muy superior",
"134 Es muy superior",
"135 Es muy superior",
"136 Es muy superior",
"137 Es muy superior",
"138 Es muy superior",
"139 Es muy superior",
"140 Es muy superior",
"141 Es muy superior",
"142 Es muy superior",
"143 Es muy superior",
"144 Es muy superior",
"145 Es un dotado",
"146 Es un dotado",
"147 Es un dotado",
"148 Es un dotado",
"149 Es un dotado",
"150 Es un dotado",
"151 Es un dotado",
"152 Es un dotado",
"153 Es un dotado",
"154 Es un dotado",
"155 Es un dotado",
"156 Es un dotado",
"157 Es un dotado",
"158 Es un dotado",
"159 Es un dotado",
"160 Es un dotado",
"161 Es muy dotado",
"162 Es muy dotado",
"163 Es muy dotado",
"164 Es muy dotado",
"165 Es muy dotado",
"166 Es muy dotado",
"167 Es muy dotado",
"168 Es muy dotado",
"169 Es muy dotado",
"170 Es muy dotado",
"171 Es muy dotado",
"172 Es muy dotado",
"173 Es muy dotado",
"174 Es muy dotado",
"175 Es muy dotado",
"176 Es muy dotado",
"177 Es muy dotado",
"178 Es muy dotado",
"179 Es muy dotado",
"180 Es muy dotado",
"181 Es muy dotado",
"182 Es brillante",
"183 Es brillante",
"184 Es brillante",
"185 Es brillante",
"186 Es brillante",
"187 Es brillante",
"188 Es brillante",
"189 Es brillante",
"190 Es brillante",
"191 Es brillante",
"192 Es brillante",
"193 Es brillante",
"194 Es brillante",
"195 Es brillante",
"196 Es brillante",
"197 Es brillante",
"198 Es brillante",
"199 Es brillante",
"200 Es brillante",
"201 Es brillante",
"202 Es brillante",
"203 Es brillante",
"204 Es brillante",
"205 Es brillante",
"206 Es brillante",
"207 Es brillante",
"208 Es brillante",
"209 Es brillante",
"210 Es brillante",
"211 Es brillante",
"212 Es brillante",
"213 Es brillante",
"214 Es brillante",
"215 Es brillante",
"216 Es brillante",
"217 Es brillante",
"218 Es brillante",
"219 Es brillante",
"220 Es brillante",
"221 Es brillante",
"222 Es brillante",
"223 Es brillante",
"224 Es brillante",
"225 Es brillante",
"226 Es brillante",
"227 Es brillante",
"228 Es brillante",
"229 Es brillante",
"230 Es brillante",
"231 Es brillante",
"232 Es brillante",
"233 Es brillante",
"234 Es brillante",
"235 Es brillante",
"236 Es brillante",
"237 Es brillante",
"238 Es brillante",
"239 Es brillante",
"240 Es brillante",
"241 Es brillante",
"242 Es brillante",
"243 Es brillante",
"244 Es brillante",
"245 Es brillante",
"246 Es brillante",
"247 Es brillante",
"248 Es brillante",
"249 Es brillante",
"250 Es brillante",
"251 No conquista al mundo porque no quiere",
"252 No conquista al mundo porque no quiere",
"253 No conquista al mundo porque no quiere",
"254 No conquista al mundo porque no quiere",
"255 No conquista al mundo porque no quiere",
"256 No conquista al mundo porque no quiere",
"257 No conquista al mundo porque no quiere",
"258 No conquista al mundo porque no quiere",
"259 No conquista al mundo porque no quiere",
"260 No conquista al mundo porque no quiere",
"261 No conquista al mundo porque no quiere",
"262 No conquista al mundo porque no quiere",
"263 No conquista al mundo porque no quiere",
"264 No conquista al mundo porque no quiere",
"265 No conquista al mundo porque no quiere",
"266 No conquista al mundo porque no quiere",
"267 No conquista al mundo porque no quiere",
"268 No conquista al mundo porque no quiere",
"269 No conquista al mundo porque no quiere",
"270 No conquista al mundo porque no quiere",
"271 No conquista al mundo porque no quiere",
"272 No conquista al mundo porque no quiere",
"273 No conquista al mundo porque no quiere",
"274 No conquista al mundo porque no quiere",
"275 No conquista al mundo porque no quiere",
"276 No conquista al mundo porque no quiere",
"277 No conquista al mundo porque no quiere",
"278 No conquista al mundo porque no quiere",
"279 No conquista al mundo porque no quiere",
"280 No conquista al mundo porque no quiere",
"281 No conquista al mundo porque no quiere",
"282 No conquista al mundo porque no quiere",
"283 No conquista al mundo porque no quiere",
"284 No conquista al mundo porque no quiere",
"285 No conquista al mundo porque no quiere",
"286 No conquista al mundo porque no quiere",
"287 No conquista al mundo porque no quiere",
"288 No conquista al mundo porque no quiere",
"289 No conquista al mundo porque no quiere",
"290 No conquista al mundo porque no quiere",
"291 No conquista al mundo porque no quiere",
"292 No conquista al mundo porque no quiere",
"293 No conquista al mundo porque no quiere",
"294 No conquista al mundo porque no quiere",
"295 No conquista al mundo porque no quiere",
"296 No conquista al mundo porque no quiere",
"297 No conquista al mundo porque no quiere",
"298 No conquista al mundo porque no quiere",
"299 No conquista al mundo porque no quiere",
"300 No conquista al mundo porque no quiere",])}
  `.trim(), m, m.mentionedJid ? {
      contextInfo: {
        mentionedJid: m.mentionedJid
      }
    } : {})
  }
  handler.help = ['Iqde (nombre)']
  handler.tags = ['fun']
  handler.command = /^iqde$/i
  handler.premium = true
  module.exports = handler
  
  function pickRandom(list) {
    return list[Math.floor(Math.random() * list.length)]
  }
  
  