let handler  = async (m, { conn }) => {
    conn.reply(m.chat,`"${pickRandom(global.verdad)}”`, m)
  }
  handler.help = ['verdad']
  handler.tags = ['verdadoreto']
  handler.command = /^verdad$/i
  handler.premium = true
  module.exports = handler
  
  function pickRandom(list) {
    return list[Math.floor(list.length * Math.random())]
  }
  
  // https://jalantikus,com/tips/kata-kata-bucin/
  global,verdad = [

    "Cuáles son las tres cosas que más te emocionan?",
    "Cuál es tu mayor miedo?",
    "Cuál es la persona más sexy de este lugar?",
    "Cuál ha sido tu mayor remordimiento?",
    "Quién de aquí tiene el mejor trasero?",
    "Quién te gusta o con quién te gustaría salir?",
    "Cuál fue la última persona a la que lamiste?",
    "Has sido o te han sido infiel?",
    "Alguna vez has salido con alguien de aquí?",
    "Qué te provoca mayor inseguridad?",
    "Cuándo fue la última vez que te orinaste en la cama?",
    "Cuál ha sido la mayor mentira que has dicho?",
    "Cuál es tu foto más vergonzosa?",
    "A quién te arrepientes de haber besado?",
    "Cuál es la historia más vergonzosa en donde has vomitado?",
    "Cuál ha sido la cosa más asquerosa que has hecho en público?",
    "Qué es algo que la mayoría de la gente cree que es verdad sobre ti, pero no lo es?",
    "En qué situación te saliste con la tuya?",
    "Qué harías si fueras del sexo opuesto durante un mes?",
    "Cuál es la cosa más valiosa que has robado?",
    "Cuál es la cosa más infantil que sigues haciendo hasta la fecha?",
    "Cuál fue la última vez que dejaste que alguien se echara la culpa por algo que tu hiciste?",
    "Qué es algo que tus amigos nunca esperarían que hicieras?",
    "Con quién de aquí te gustaría salir?",
    "Cuál ha sido la mentira más dolorosa que le has dicho a alguien?",
    "Cuál es la cosa más mala que le has hecho a alguien (y no se lo merecía)?",
    "Qué es algo que las personas piensan que nunca harías, pero te gustaría hacer?",
    "Cuál ha sido el peor encuentro que has tenido con un policía?",
    "Cuál es la cosa más tonta a la que le tienes un apego emocional?",
    "Dónde ha sido el lugar más extraño en el que has orinado?",
    "Cuál es la cosa más vergonzosa que tus padres te han visto haciendo?",
    "Qué secreto le contaste a alguien en confianza y se lo contó a un montón de personas?",
    "Cuál ha sido el momento más inapropiado en el que te has echado un gas?",
    "Cuál ha sido el sueño más aterrador que has tenido?",
    "Cuál es la cosa más vergonzosa que tienes en tu habitación?",
    "Por qué terminaste con tu última novia o último novio?",
    "Cuál ha sido la cosa más estúpida que has hecho?",
    "Cuál es la cosa más asquerosa que ha salido de tu cuerpo?",
    "Cuál es la cosa que más te gusta que haga tu novio o novia?",
    "Qué cosa horrible has tenido ocultar con una mentira?",
    "Qué persona nunca te pudo corresponder?",
    "Qué es algo que nunca le has contado a nadie?",
    "Cuál es el hábito más asqueroso que tienes?",
    "Qué fotos o videos desearías que no existieran?",
    "Cuál ha sido la broma más cruel que le has hecho a alguien?",
    "Cuál es la cosa más vergonzosa que has publicado en redes sociales?",
    "Cuál es la cosa más terrible que has hecho que nadie la ha descubierto?",
    "Cuál ha sido el encuentro romántico más extraño que has tenido?",
    "Cuál es la cosa más asquerosa que has tenido en la boca?",
    "Cuál ha sido el apodo más vergonzoso que has tenido?",
    "Cuál es la serie de mensajes más vergonzosa que tienes en tu teléfono?",
    "Cuál ha sido la cosa más extraña que has hecho por un novio o una novia?",
    "Es verdad que (cualquier cosa que tú o el grupo sospeches/sospechen que hizo esa persona)?",
    "Cuándo fue la última vez que arrojaste o pegaste un moco en un lugar inapropiado?",
    "Qué esperas que tus padres nunca descubran?",
    "Por qué motivo te juzgarían las personas aquí presentes?",
    "Qué es lo más infantil que has hecho últimamente?",
"Hay algo que ocultes a tus padres?",
"Y a tus amigos?",
"Cuál es tu mayor miedo?",
"Alguna vez te ha arrestado la policía?",
"Alguna vez has robado?",
"Alguna vez has cometido un delito?",
"Hablas contigo mismo en voz alta?",
"Qué es lo peor que has publicado en una red social?",
"Alguna vez has intentado ligar a través de una red social?",
"Cuál es la peor apuesta que has hecho?",
"Cuál ha sido tu mayor mentira?",
"Cuál es la broma más desagradable que has hecho?",
"Qué harías si fueras rico?",
"Qué harías si tuvieras el poder de la invisibilidad?",
"Qué harías si pudieras viajar en el tiempo?",
"Si pudieras dejar de ver a alguien, a quién elegirías?",
"A quién te llevarías a una isla desierta?",
"Qué harías si te encontraras un maletín lleno de dinero por la calle?",
"Alguna persona de esta habitación que antes te caía mal?",
"Cuál es la persona de esta habitación que peor te cae?",
"Qué es lo peor que has hecho por amor?",
"Qué canción escuchas en secreto?",
"Cuál ha sido la peor etapa de tu vida?",
"Cuál es el hábito más desagradable que tienes?",
"Qué es lo más asqueroso que has comido?",
"Cuál es tu foto más vergonzosa?",
"Cantas en la ducha?",
"Bailas en la ducha?",
"Cuánto tiempo has estado sin ducharte?",
"Cuál es tu talento más raro?",
"Qué es lo peor que le has dicho a tus padres?",
"Qué prefieres, villano o superhéroe?",
"Podrías pasar dos meses sin teléfono móvil?",
"Le mentirías a un amigo para no hacerle daño?",
"Si fueras otra persona, quién te gustaría ser?",
"Has empezado un rumor sobre alguien para hacerle daño?",
"Serías capaz de matar a alguien?",
"Cuál ha sido tu peor fracaso?",
"Qué es lo más surrealista que te ha pasado?",
"Cuál es el sueño más surrealista que has tenido?",
"Qué es lo más ridículo que te ha pasado por la calle?",
"Qué es lo más ridículo que te ha pasado durante una cita?",
"Qué es lo peor que has hecho estando borracho?",
"Alguna vez has orinado en la piscina o en la ducha?",
"Cuál es la mayor locura que has hecho?",
"Cuál es el vídeo de Youtube que más gracia te ha hecho?",
"Te vestirías con ropa del sexo opuesto?",
"La última vez que te tiraste un pedo?",
"Qué harías si te quedas sin papel en un baño público?",
"Qué es lo peor que ha salido de tu cuerpo y lo peor que ha entrado?",
"Has olfateado ropa interior para saber si estaba limpia?",
"Cuál ha sido el piropo más extraño que te han lanzado y el insulto más extraño?",
"Quién es tu amor de la infancia y tu amor platónico?",
"Qué es lo peor que has hecho por dinero?",
"Has hecho alguna broma telefónica subida de tono?",
"Cómo conquistarías a un hombre o una mujer?",
"Cómo sería tu cita perfecta?",
"Cómo sería tu pareja perfecta?",
"Cómo sería tu experiencia sexual perfecta?",
"Cuál es la parte que más te gusta de tu cuerpo?",
"Cómo fue tu último sueño erótico?",
"En quién pensaste la última vez que te masturbaste?",
"Con qué frecuencia te masturbas?",
"Con cuántas personas te has acostado?",
"Quién es la persona más sexy de esta habitación?",
"Lo harías con alguien de esta habitación?",
"Con qué persona famosa te gustaría tener sexo?",
"Tienes algún fetiche raro?",
"Qué tipo de pornografía ves?",
"Qué páginas de pornografía ves?",
"Has fingido un orgasmo?",
"Qué palabras te excitan?",
"Te gustan los disfraces eróticos?",
"Podrías definir el orgasmo en una palabra?",
"Has tenido sexo telefónico alguna vez?",
"Te has besado o lo has hecho con alguien de tu mismo sexo?",
"Qué prefieres, dormir o tener sexo?",
"Y entre comer y tener sexo?",
"Quién tiene mejor físico de esta habitación?",
"Has mentido acerca de tu vida sexual?",
"Serías una persona del sexo opuesto durante un mes?",
"Utilizas juguetes sexuales?",
"Cuál es la propuesta más indecente que te han hecho?",
"Alguna vez has usado anticonceptivos de emergencia?",
"Compartirías cama con otra persona?",
"Has fantaseado con alguien más?",
"Alguna vez has ocultado algo a tu pareja?",
"Qué es lo que más te gusta de tu pareja?",
"Cuál es la parte de tu pareja que más te gusta?",
"Qué es lo que más te molesta de tu pareja?",
"Alguna vez te has negado a tener sexo con tu pareja?",
"Cuál es la mayor mentira que has contado a tu pareja?",
"Qué es lo más estúpido que le has hecho a tu pareja teniendo sexo?",
"Te atreverías a imitar a tu pareja?",
"De todas las parejas que has tenido, quién besa mejor?",
"Y con cuál has tenido mejor sexo?",
"Qué harías si tu relación acabara ahora?",
"Qué harías si encontraras a tu pareja con otra persona?",
"Has sido infiel?",
"Perdonarías una infidelidad?",
"Qué piensas de la familia de tu pareja?",
"Le harías un striptease a tu pareja?",
"Podrías definir a tu pareja con tres palabras?",
"A quién quieres más?", "A tu mascota o a tu pareja?",
"Cambiarías de suegros?",
"Te tatuarías algo en pareja?",
"Te pondrías la ropa interior de tu pareja?",
"Cómo rompiste con tu último novio o novia?",
"Alguna vez has pensado en ser infiel?",
"Cambiarías a tu pareja por  millones de dólares?",
"Te gustaría casarte?",
"Te gustaría tener hijos?",
"Te  consideras una persona celosa?",
"Qué es lo peor que has hecho por celos?",
"Qué ha sido lo último que buscaste en tu teléfono?",
"Si tuvieras que elegir entre ir desnudo o que tus pensamientos aparezcan escritos sobre tu cabeza para que todos los lean, cuál elegirías?",
"Alguna vez has visto a tus padres haciéndolo?",
"Después que se te caiga un trozo de comida, cuanto es el máximo tiempo que estuvo en el suelo y luego te la comiste?",
"Alguna vez te has comido un moco?",
"Qué es lo primero que harías si te levantaras un día siendo del sexo opuesto?",
"Alguna vez has hecho pis en una piscina?",
"Quién crees que es la persona peor vestida en esta sala?",
"Alguna vez te has tirado un pedo en un ascensor?",
"Verdadero o falso Estás enamorado de [completa el espacio en blanco]?",
"En que cosas piensas cuando te sientas en el inodoro?",
"Tuviste un amigo imaginario cuando eras pequeño?",
"Alguna vez has practicado besos con un espejo?",
"Alguna vez tus padres te han dado la charla de “las flores y las abejas”?",
"Cuál es tu placer prohibido?",
"Cuál es tu peor hábito?",
"Estás en el baño haciendo caca y de repente te das cuenta de que no hay papel, que haces?",
"Alguna vez te has chocado contra una pared o farola por ir despistado?",
"Cantas en la ducha?",
"Cuando te has hecho pis encima por última vez?",
"Cuál ha sido tu momento más ridículo en público?",
"Alguna vez te has tirado un pedo fuerte delante de mucha gente?",
"Alguna vez hablas contigo mismo en el espejo?",
"Qué es lo que te da más vergüenza de tu historial de búsqueda?",
"Alguna vez te has sacado una foto sexy o desnudo/a?",
"Duermes con un peluche?",
"Babeas cuando duermes?",
"Hablas dormido?",
"Roncas mucho?",
"Quién es tu amor secreto?",
"Crees que [completar el nombre] es muy guapo(a)?",
"Quién te cae peor de esta sala y por qué?",
"Cómo es tu chico o chica de los sueños?",
"Cuál es tu canción favorita para ir a la ducha?",
"Quién es la persona más sexy de esta habitación?",
"Cómo calificarías el físico de [insertar nombre] en una escala del 1 al 10?",
"Preferirías tener sexo con [insertar nombre] en secreto o no tener relaciones sexuales con esa persona, pero que todos piensen que lo habéis hecho?",
"Qué es lo que menos te gusta de mí?",
"De qué color es la ropa interior que estás usando ahora?",
"Qué es lo último que has enviado en un mensaje de texto?",
"Si estuvieras rescatando personas de incendio en un edificio y tuvieras que dejar a una persona de esta habitación, quién sería?",
"Crees que te casarás con tu novia/novio actual?",
"Con qué frecuencia lavas tu ropa interior?",
"Alguna vez has probado tu cera del oído?",
"Alguna vez te has tirado un pedo y luego has culpado a alguien más?",
"Alguna vez has probado tu sudor?",
"Qué es lo más ilegal que has hecho en tu vida?",
"Quieres más a tu padre o a tu madre?",
"Cambiarías a tu mascota por un millón de euros?",
"Cuáles son las cosas que más te irritan?",
"Si tu pareja te permitiese tener más parejas aunque estéis juntos, lo harías Con quién elegirías estar?",
"Preferirías perder tus órganos sexuales para siempre o engordar 100kilos?",
"Elegirías salvar a 10 personas sin que nadie lo sepa, o no salvarlas pero que todos te admirasen como si lo hubieras hecho?",
"Si solo pudieras escuchar una canción por el resto de tu vida, cuál sería?",
"Si perdieras un día de tu vida cada vez que dijeras una palabrota, intentarías no hacerlo?",
"Preferirías vivir sin internet o sin aire acondicionado o calefacción?",
"Si alguien te ofrece un millón de euros por romper con tu novia / novio, lo harías?",
"Si pudieras renacer en cualquier época, en cual elegirías?",
"Si pudieras retroceder en el tiempo para borrar una cosa que hayas dicho o hecho, cuál sería?",
"Alguna vez tu pareja te ha avergonzado?",
"Alguna vez has pensado en engañar a tu pareja?",
"Si pudieras volverte invisible de repente, qué harías?",
"Alguna vez te han pillado mirando a alguien (las zonas eróticas)?",
"Alguna vez has saludado a alguien pensando que te había visto, pero en realidad no lo había hecho? Qué hiciste cuando te diste cuenta?",
"Cuánto ha sido el mayor tiempo que has estado en el baño y por qué?",
"Alguna vez has llorado porque echabas de menos a tus padres?",
"Prefieres ser atrapado hurgándote la nariz o que te den una colleja?",
"Describe el sueño más extraño que hayas tenido. Te gustó?",
"Alguna vez has publicado algo en las redes sociales de lo que te arrepientas?",
"Cuál es tu mayor miedo?",
"Haces pis en la ducha?",
"Alguna vez has plantado a alguien?",
"El mundo termina la próxima semana y puedes hacer lo que quieras (incluso si es ilegal). Qué harías?",
"Te pondrías la camisa al revés durante todo un día si alguien te pagara 20€?",
"Qué es lo más inmaduro que todavía haces?",
"Como de lejos llegarías para seducir al chico o chica de tus sueños?",
"Alguna vez has robado un libro de la biblioteca?",
"Hay alguien que fijas que te cae bien pero en realidad no? Quien es?",
"Qué película para niños podrías ver una y otra vez?",
"Te huelen mucho los pies?",
"Tienes algún mote ridículo?",
"Cuánto chocolate/helado has comido de una sola vez como máximo?",
"Alguna vez has chocado a otro coche mientras aparcabas y te has hecho el despistado/a?",
"Si tuvieras que besarte con cualquier personaje de Disney, con quién sería?",
"Alguna vez has visto una película que sabías que no deberías?",
"Alguna vez has querido probar Juegos de Rol (como Dragones&Mazmorras)?",
"Con qué aplicación de tu teléfono pierdes más tiempo?",
"Alguna vez has fingido estar enfermo para evitar algo que no te apetecía Si es así, qué era lo que evitaste?",
"Cuál es la mayor cantidad de comida que has comido en una sola sentada?",
"Bailas cuando estás solo?",
"Qué canción de la radio cantas cada vez que aparece?",
"Duermes con pijama o sin pijama?",
"Tienes miedo a la oscuridad?",
"Qué producto de teletienda te comprarías en secreto?",
"Todavía tomas baños de burbujas?",
"Si estuvieras en casa solo todo el día, qué harías?",
"Cuántos selfies te tomas al día?",
"Qué cosas has hecho o dicho para aparentar que eres guay o hacerte el interesante?",
"Cuándo fue la última vez que te cepillaste los dientes?",
"Cómo son tus pijamas favoritos?",
"Has salido de fiesta con tus padres? Te gustó?",
"Alguna vez te han pillado haciendo algo que no debías?",
"Qué parte de tu cuerpo te encanta y qué parte odias?",
"Cuando fue la última vez que tuviste piojos?",
"Como era el último vídeo porno que has visto?",
"Lames tu plato si te ha gustado mucho la comida?",
"Qué es algo que nadie más conoce de ti?",
"Has escrito en un diario alguna vez?",
"Cuál es la peor cita en la que has estado? Por qué fue tan mal?",
"Alguna vez te has enamorado del novio de una amiga?",
"Si tuvieras que besarte con un chico de tu colegio/trabajo, con quién sería?",
"Preferirías pasar un mes sin lavarte el pelo o una semana sin usar sostén?",
"Alguna vez le has pedido una cita tú a alguien?",
"Alguna vez te has enamorado de una persona al menos 10 años mayor que tú?",
"Quién es la persona que te ha besado peor en tu vida?",
"De qué tamaño es tu sostén?",
"Usas tanga o bragas anchas?",
"De vez en cuando te quedas admirándote en el espejo?",
"Alguna vez te has enamorado de alguien y que al enterarse te haya rechazado?",
"Alguna vez te han dejado plantada en una cita?",
"Cuál es la cosa más ridícula que has hecho con respecto a alguien que te gustase?",
"Te gusta o gustaba “Crepúsculo”?",
"Quién te gusta más? Hagrid, Dumbledore o Dobby?",
"Si pudieras casarte con cualquier famoso, con cuál sería?",
"Qué haces para sentirte “sexy”?",
"De quién estás enamorada?",
"Qué peinado siempre has querido, pero nunca has probado?",
"Cuál es la cosa más embarazosa que has dicho o hecho delante de alguien que te gusta?",
"Qué parte de tu cuerpo amas y qué parte odias?",
"Si pudieras cambiar una cosa de tu cuerpo, cuál sería?",
"Con quién fue tu primer beso? Te gustó?",
"De quién estás celoso?",
"Si pudieras ser otra chica en la escuela, quién serías?",
"Besarías a un chico en la primera cita? Harías más que eso?",
"Quiénes son los 5 chicos más lindos de la clase Clasifícalos?",
"Cuántos niños quieres tener en el futuro?",
"A quién odias más?",
"Si pudieras salir en una cita con una persona famosa, con cuál sería?",
"Si estuvieras en una isla desierta, con quién te gustaría quedarte de nuestros amigos?",
"Alguna vez has coqueteado con los hermanos de tu mejor amiga?",
"Alguna vez te han dejado? Cuál fue el motivo?",
"Te gustan más deportistas, nerds, o chicos malos?",
"Qué es lo que te resulta más atractivo en un hombre?",
" Qué es lo que te resulta más atractivo en una chica?",
"Te operarías estéticamente?",
"Prefieres ser un chico o una chica? Por qué?",
"Describe tu mayor pasión?",
"Si pudieras comer cualquier cosa que quisieras sin engordar, que cosa sería?",
"Pasarías un año sin tu teléfono si eso significara que podrías estar con la persona de tus sueños?",
"Te quedas atrapada en una isla de desierta y solo puedes traer cinco cosas. Cuales son?",
"Si solo pudieras elegir un peinado para el resto de tu vida, elegirías pelo rizado o liso?",
"Podrías pasarte toda la vida sin maquillarte?",
"Saldrías con alguien más bajo que tú?",
"Si alguien te pagara 100€ por tu sujetador (el que llevas puesto) se lo venderías?",
"Cuál es la peor cita en la que has estado?", "Por qué fue tan mal?",
"Alguna vez te has enamorado del novio de una amiga?",
"Si tuvieras que besarte con un chico de tu colegio/trabajo, con quién sería?",
"Preferirías pasar un mes sin lavarte el pelo o una semana sin usar sostén?",
"Alguna vez le has pedido una cita tú a alguien?",
"Alguna vez te has enamorado de una persona al menos 10 años mayor que tú?",
"Quién es la persona que te ha besado peor en tu vida?",
"De qué tamaño es tu sostén?",
"Usas tanga o bragas anchas?",
"De vez en cuando te quedas admirándote en el espejo?",
"Alguna vez te has enamorado de alguien y que al enterarse te haya rechazado?",
"Alguna vez te han dejado plantada en una cita?",
"Cuál es la cosa más ridícula que has hecho con respecto a alguien que te gustase?",
"Te gusta o gustaba “Crepúsculo”?",
"Quién te gusta más?", "Hagrid, Dumbledore o Dobby?",
"Si pudieras casarte con cualquier famoso, con cuál sería?",
"Qué haces para sentirte “sexy”?",
"De quién estás enamorada?",
"Qué peinado siempre has querido, pero nunca has probado?",
"Cuál es la cosa más embarazosa que has dicho o hecho delante de alguien que te gusta?",
"Qué parte de tu cuerpo amas y qué parte odias?",
"Si pudieras cambiar una cosa de tu cuerpo, cuál sería?",
"Con quién fue tu primer beso?", "Te gustó?",
"De quién estás celoso?",
"Si pudieras ser otra chica en la escuela, quién serías?",
"Besarías a un chico en la primera cita?", "Harías más que eso?",
"Quiénes son los 5 chicos más lindos de la clase Clasifícalos?",
"Cuántos niños quieres tener en el futuro?",
"A quién odias más?",
"Si pudieras salir en una cita con una persona famosa, con cuál sería?",
"Si estuvieras en una isla desierta, con quién te gustaría quedarte de nuestros amigos?",
"Alguna vez has coqueteado con los hermanos de tu mejor amiga?",
"Alguna vez te han dejado?", "Cuál fue el motivo?",
"Te gustan más deportistas, nerds, o chicos malos?",
"Qué es lo que te resulta más atractivo en un hombre?",
" Qué es lo que te resulta más atractivo en una chica?",
"Te operarías estéticamente?",
"Prefieres ser un chico o una chica?", "Por qué?",
"Describe tu mayor pasión?",
"Si pudieras comer cualquier cosa que quisieras sin engordar, que cosa sería?",
"Pasarías un año sin tu teléfono si eso significara que podrías estar con la persona de tus sueños?",
"Te quedas atrapada en una isla de desierta y solo puedes traer cinco cosas. Cuales son?",
"Si solo pudieras elegir un peinado para el resto de tu vida, elegirías pelo rizado o liso?",
"Podrías pasarte toda la vida sin maquillarte?",
"Saldrías con alguien más bajo que tú?",
"Si alguien te pagara 100€ por tu sujetador (el que llevas puesto) se lo venderías?",
"Si tuvieras que elegir entre salir con una chica fea que sea buena en la cama o salir con una atractiva que es mala en la cama, cuál elegirías?",
"Si pudieras ser invisible, a quién espiarías?",
"Quiénes son las 5 chicas qué más te gustan de la escuela?", "Y de nuestra clase?",
"Con quién te besarías de esta habitación?",
"Si pudieras salir con una novia de tus amigos, con quién saldrías?",
"Cuál es tu parte favorita de tu cuerpo?",
"Cuándo fue la última vez que te flexionaste los músculos frente al espejo?",
"Describe a tu pareja perfecta?",
"Has estado enamorado?",
"Rubias o morenas?",
"Qué cosas te excitan más?",
"Si tus padres odiaran a tu novia, la dejarías?",
"Si tu novia odiara tu mejor amiga, qué harías?",
"De qué celebridad estás enamorado?",
"Tomarías esteroides?",
"Alguna vez te has pillado por la novia de un amigo?",
"De quién estás celoso?",
"Quién crees que es la más chica más bonita de nuestro grupo?",
"Cuál ha sido el mayor disgusto de tu vida?",
"Alguna vez has sido rechazado por alguien?",
"Si tuvieras que elegir entre ser pobre e inteligente o ser rico y tonto, qué elegirías?",
"En que cosas le has mentido a tu pareja?",
"Alguna vez has engañado a tu pareja?",
"Saldrías con una mujer muy mayor?",
"Boxers o calzoncillos?",
"Cuándo fue la última vez que lloraste?",
"Si pudieras besarte con la chica de otra persona, con quién sería?",
"Te has besado con un chico?", "Si es que no, lo harías?",
"Si cada vez que miraras el cuerpo de una chica, aumentaras 2kilos, con qué frecuencia lo harías?",
"Alguna vez has mentido sobre tu edad?",
"Alguna vez te has enamorado a primera vista?",
"Si una chica que no te gusta estuviera enamorada de ti, qué harías al respecto?",
"Y si ella fuera tu amiga?",
"Qué harías si descubrieras que a tu novia le gusta alguien más?",
"Si formases un grupo de música con tus amigos, tu que rol tendrías?",
"A quién odiarías ver desnudo?",
"Cuánto tiempo has pasado sin ducharte?",
"Si solo pudieras enviar mensajes de texto a una persona por el resto de tu vida, pero nunca pudieras hablar con esa persona cara a cara, quién sería?",
"Cuánto tiempo has pasado sin cepillarte los dientes?",
"Qué cosa nunca comerías en una primera cita?",
"Hay algo que hayas visto que desearías olvidar?",
"Si pudieras reencarnarte en el cuerpo de alguien, en quién te gustaría convertirte?",
"Si cambiaras de sexo por un día, qué harías?",
"Qué comida nunca pedirías en un restaurante?",
"Si tu coche se estropea en el medio de la carretera, quién de esta habitación sería la última persona a la que llamarías? Por qué?",
"Cuál es el conocimiento más inútil que tienes?",
"Qué cosa aprendiste en el colegio que desearías poder olvidar?",
"Es mejor usar champú como jabón o jabón como champú?",
"Si te quedas sin papel higiénico, considerarías limpiarte con el rollo vacío?",
"Cuál sería la peor parte de que te bajen los pantalones frente a alguien que te gusta?",
"Si solo pudieras usar una mala palabra por el resto de tu vida, cuál elegirías?",
"Quién crees que es la Beyonce del grupo?",
"Preferirías comer comida para perros o comida para gatos?",
"Si tuvieras nueve vidas, qué harías que no haces ahora?",
"Si pudieras gastar una broma a alguien sin ser atrapado, a quién se la jugarías?",
"Cuál sería la broma?",
"Has fingido alguna vez que te gusta un regalo?", "Cómo fingiste?",
"Prefieres no ducharte durante un mes o comer la misma comida todos los días durante un mes?",
"A que animal crees que te pareces más?",
"Si pudieras elegir entre no sudar nunca por el resto de tu vida o nunca tener que usar el baño, cuál elegirías?",
"Preferirías tener muchas novias al mismo tiempo o estar con una sola que quieras mucho?",
"Prefieres no jugar nunca más a fútbol o no jugar nunca más a una consola?",
"Si la persona que te gusta te dijera que le gusta tu mejor amigo, qué harías?",
"Qué pasaría si tu mejor amigo te dijera que le gusta la persona que a ti te gusta?",
"Si supieras que el novio de tu amiga la está engañando, qué harías?",
"Alguna vez has dicho una mentira sobre tu mejor amigo para tu quedar mejor?",
"Cuál fue tu primera impresión de [complete el nombre de una persona en la sala]?",
"Si tuvieras que salir con el novio de una amiga/o, con quién saldrías?",
"Quién es más sexy?", "Tú o tu amigo?",
"Alguna vez has compartido un secreto de tu amigo con alguien más?",
"Califica a todos en la sala del 1 al 10, siendo 10 el más sexy?",
"Compartirías un cepillo de dientes con tu mejor amigo?",
"Califica a todos en la sala del 1 al 10, siendo 10 la mejor personalidad?",
"Alguna vez has ignorado un mensaje el móvil de un amigo?", "Por qué lo hiciste?",
"Alguna vez le has mentido a tu mejor amigo?",
"Dejarías que un amigo hiciera trampa en un examen?",
"Si tu amigo te pidiera que mintieras por el y supieras que te meterías en problemas, lo harías?",
"Si una de tus amigas estuviera siendo infiel con el novio de otra amiga, qué harías?",
"Cambiarías de amigos si te diesen 1.000.000€?",
"Si tuvieras que elegir, de quién dejarías de ser amigo?",
"Nombra una cosa que cambiarías sobre cada persona en esta sala?",
"Si tuvieras que cambiar a un amigo por la persona de tus sueños, qué amigo elegirías?",
"Cuál fue tu primera impresión del novio de tu mejor amiga?",
"Qué piensas de él ahora?",
"Si alguien te pregunta cómo es tu mejor amiga/o, cómo la/o describirías?",
"Te ganas un viaje como premio y puedes traer dos personas. A quién eliges?",
"En un viaje de una noche, preferirías compartir una cama con tu mejor amiga o su novio?",
"Si pudieras intercambiar una característica física con tu mejor amigo, qué sería?",
"Alguna vez has contado un secreto que te dijeron que guardes?",
"Si tu mejor amigo tuviese mal olor, se lo dirías?",
"Qué es lo más molesto de tu mejor amigo?",
"Con quién crees que tu amiga debería salir en lugar de su novio actual?",
"Crees que el novio de tu amiga es atractivo?",
"Estarías con él si estuvieras segura de que nunca lo sabrá?",
"Alguna vez has abandonado a tu amiga por un chico?",
"Si tu amiga y tu novio estuvieran en peligro, a quién intentarías salvar primero?",
"Actualmente estás enamorado de alguien?",
"Describe cómo es la persona que te gusta?",
"Cómo es la personalidad de la persona que te gusta?",
"Hay algo sobre tu vida que cambiarías?",
"A quién odias y por qué?",
"Qué es lo que más te molesta de tu vida?",
"Cuántas personas has besado?",
"Qué es lo que más te excita?",
"Si pudieras salir con cualquiera en el mundo, con quién saldrías?",
"Prefieres ser flaco y muy peludo o gordo y lampiño?",
"Describe tu noche de fiesta perfecta?",
"Alguna vez saldrías con dos personas a la vez si no te pillasen?",
"Tienes que eliminar todas las aplicaciones en tu móvil excepto tres. Cuales son?",
"Alguna vez has enviado fotos tuyas desnuda/o por el móvil?",
"Alguna vez has recibido fotos de alguien desnudo/a? De quién era? Cuál fue tu reacción?, Te gustó o no?",
"Alguna vez te has enfadado con un amigo por publicar una foto donde no salías bien?",
"Alguna vez te has enamorado de un profesor?",
"Quién crees que sería la persona que besa mejor (Enumera algunas personas para que elijan)?",
"Alguna vez le has enviado a alguien un mensaje que era para otra persona?",
"Quién crees que es la persona más sexy de nuestra clase?",
"Cuál es la cualidad más atractiva de una persona?",
"Cuál es el factor decisivo más importante para elegir una pareja para ti?",
"Podrías acostarte con alguien en la primera cita?", "Por qué?",
"Alguna vez te has arrepentido de algo que hiciste para llamar la atención?",
"Alguna vez serías malo con alguien si eso significara que pudieras salvar a tu amigo de que pase vergüenza (por ejemplo culpar a otra persona de algo que ha hecho un amigo tuyo)?",
"De la gente de nuestra escuela, qué alumno crees que haría mejor de profesor?",
"Irías a una escuela que solo te dejan llevar uniforme?",
"Que cosas crees que hacen a un chico o chica la pareja perfecta?",
"Si pudieras ganar un millón de euros, dejarías la escuela?",
"Cuál es tu peor hábito?",
"Qué cosas haces que no quieres que nadie sepa?",
"Acosas a alguien por las redes sociales mirando todo el tiempo su perfil sin que lo sepa A quien?",
"A quién tienes más ganas de besar?",
"Si tuvieras que desnudarte frente a una sola persona en esta sala, frente a quién sería?",
"Si aún no has tenido tu primer beso, con quién en esta habitación quieres tener tu primer beso?",
"De las personas en esta sala, con quién saldrías?",
"Describe lo más atractivo de cada persona en esta sala?",
"Quién crees que es más coqueto?",
"Quién tiene la mejor sonrisa?",
"Quién tiene la nariz más bonita?",
" Quién tiene los ojos más bonitos?",
"Quién es el más divertido de esta sala?",
"Qué cosa nunca harías frente a alguien que te gusta?",
"Con qué frecuencia te miras en el espejo cuando estás en una cita?",
"Quién crees que sería el mejor besador(a)?",
"Quién crees que tiene los mejores movimientos de baile?",
"Si pudieras tener una característica física de alguien en esta sala, cuál sería?",
"Cuál es tu fantasía sexual más salvaje?",
"Califícame en una escala de 1 a 10, siendo 10 el más atractivo?",
"Si fuera un alimento, qué sería y cómo me comerías?",
"Elegirías una relación salvaje y caliente o una tranquila y estable?",
"Si tuvieras una semana para vivir y tuvieras que casarte con alguien en esta sala, con quién sería?",
"Si solo tuvieras 24 horas para vivir y pudieras hacer cualquier cosa con cualquier persona en esta sala, con quién sería y qué harías con esa persona?",
"Qué es lo que más te excita sexualmente?",
"Y lo que menos?",
"Saldrías conmigo si fuera la última persona en la tierra?",
"Qué es lo más sexy que has hecho alguna vez?",
"Qué es lo más sexy de [complete el nombre de una persona en la sala]?",
"Si pudieras ir a una cita romántica con alguien en esta sala, a quién elegirías?",
"Si tuvieras que eliminar una aplicación de tu teléfono, cuál sería?",
"Cuál es tu mayor miedo en una relación?",
"Ve por la habitación y di una cosa positiva y una negativa de cada persona?",
"Cuál es un hecho más perturbador de ti?",
"Alguna vez has fumado?",
"Alguna vez has probado las drogas?", "Cuales?",
"Cuantas veces te has emborrachado?",
"Cuál es la cosa más loca que has hecho mientras estabas borracho?",
"Si estuvieras atrapado en una isla durante tres días, cuáles serían las tres personas en esta habitación que llevarías contigo y por qué?",
"Irías a una playa nudista?",
"Quién es la persona más molesta en esta sala?",
"Todavía eres virgen?",
"Si tuvieras que casarte con alguien en esta sala, con quién sería?",
"Tiene piercings escondidos o tatuajes?",
"Cuánto duró tu relación más larga?",
"Si pudieras tener a una persona famosa siguiéndote en Instagram, quién sería?",
"Tienes que eliminar 5 personas de tu Instagram. Nómbralos?",
"Quieres casarte algún día?",
"Quieres tener hijos?", "Cuántos?",
"Tendrías una relación a larga distancia?",
"Describe a la persona de tus sueños?",
"Qué harías si descubrieras que han eliminado las escuelas y ya no hace falta ir?",
"Si tú novia o novio rompiera contigo en la escuela, qué harías?",
"Si tuvieras el poder de despedir a un maestro, a quién despedirías?",
"Baloncesto, béisbol o fútbol?",
"Cuál ha sido tu primer trabajo?",
"Si todavía no tienes uno, dónde te gustaría trabajar?",
"Cuántas horas estarías con el ordenador si no tuvieras escuela o cosas que hacer?",
"Cómo de alto quieres llegar a ser?",
"Cuál es tu mayor temor sobre la universidad?",
"Qué es lo que más te emociona del futuro?",
"Te gustaría que tu mejor amigo vaya a la misma universidad que tú?",
"Te gustaría que su novio o novia actual vaya a la misma universidad que tú?",
"Quién crees que es la persona más popular del colegio?",
"Cuál es tu trabajo soñado?",
"Hay algún rumor sobre ti?",
"Alguna vez te han pillado copiando?",
"Si tuvieras el poder de nombrar a una persona maestro, a quién sería?",
"Si pudieras planear una broma para la clase, sabiendo que nunca te pillarían, qué broma sería?",
"Alguna vez te has copiado en una prueba?",
"Alguna vez te has enamorado de un profesor?", "Quién?",
"Alguna vez has besado a alguien en la escuela?",
"Con quién no te gustaría sentarte nunca en clase?",
"Alguna vez has llegado tarde a clase?",
"Qué es lo más ridículo que has hecho frente a un profesor?",
"Alguna vez has pegado chicle debajo de un escritorio?",
"Si tuvieras que tomar una clase por el resto de tu vida, qué clase sería y quién sería el maestro/a?",
"Si quisieras acostarte con alguien en el campus, dónde lo harías?",
"Alguna vez te has peleado en la escuela?",
"Cuál ha sido la peor nota que has sacado en un examen?",
"Alguna vez te has quedado dormido en clase?",
"Alguna vez te han expulsado?",
"Si fueras invisible, echarías un ojo en el otro vestuario?",
"Si es así, a quién te gustaría ver?",
"Quién es el mejor profesor de nuestra escuela?",
"Cuál es la peor clase para tener a primera hora?",
"Si tuvieras que irte a vivir con una persona de otro curso, con quien te irías?",
"Alguna vez te has desnudado frente a alguien?",
"Alguna vez has hecho sexting?",
"Alguna vez has estado en una playa nudista?", "Considerarías ir?",
"Alguna vez considerarías posar desnuda para unas fotos?", "Y si fueran solo para ti y privadas?",
"Quién te ha visto sin ropa?",
"Cuantas veces ves porno a la semana?",
"Alguna vez has enviado una selfie desnuda?", "A quién se la enviarías?",
"Qué es lo más sucio que has buscado en Internet?",
"Con quién preferirías acostarte, entre todos los de aquí?",
"Cuál es la parte del cuerpo que más te gusta en una persona del sexo opuesto?",
"Cuántas personas has besado?",
"Alguna vez te has sentido atraído(a) por el mismo sexo?",
"Cuándo y dónde fue tu primer beso?", "Con quién fue?",
"Cuándo perdiste la virginidad y con quién la perdiste?",
"Cuál es tu mayor fantasía sexual?",
"Saldrías con un alguien mayor?", "Qué edad es demasiado viejo?",
"Duermes desnudo?",
"Cuánto dinero tendríamos que pagar para que muestres los pechos?",
"Has tenido follamigos?", "Cuantos?",
"Si tuvieras que ir nadar desnudo con alguien, con quién irías de esta habitación?",
"Si te pago 100€, usarías tu ropa más sexy para ir a clase?",

]