let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`"${pickRandom(global.reto)}”`, m)
}
handler.help = ['reto']
handler.tags = ['verdadoreto']
handler.command = /^reto$/i
handler.premium = true
module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

// https://jalantikus,com/tips/kata-kata-bucin/
global,reto = [


"Lamer mantequilla de maní o algún otro tipo de crema del brazo de alguien",
"Cerrar los ojos y dejar que otro jugador te dé una cucharada de cualquier cosa que haya en la nevera",
"Ir desnudo, a nadar en una piscina o corretear por la casa",
"Dejar que una persona te dé unos azotes tan fuertes como quiera, en el trasero",
"Dejar un mensaje de voz para uno de tus ex",
"Fingir un gran “O” mientras miras a alguien a los ojos",
"Comer la mitad de una cebolla sin llorar",
"Dejar que alguien lea tus ‘mensajes de texto picantes’ en voz alta",   
"Besar apasionadamente tu mano",  
"Aplicar para un trabajo online realmente extraño",
"Publicar un mensaje en redes sociales diciendo que estás considerando dejar tu trabajo o estudios para convertirte en un payaso profesional",
"Darle a alguien en la sala un masaje de pies",
"Llamar a los padres de tu novia / novio y decirle cuánto quieres a su hijo (a)",
"Lamer un neumático del auto de alguien más",
"Dejar que todos los demás jugadores elijan algo con lo que te laves los dientes",
"Ir afuera y cortar 50 hojas de césped con un par de tijeras",
"Conseguir un Cheeto Picante y metértelo en la nariz durante  minutos",
"Comer una cucharada de ketchup",
"Tragarse un huevo crudo",
"Encontrar algo apestoso en la basura y dejártelo en la cabeza durante un minuto completo",
"Mantener la nariz bajo la axila de otro jugador durante treinta segundos",
"Darle a otro jugador tu teléfono y dejarlo enviar un mensaje a cualquiera de la lista de contactos",
"Permitir que otro jugador te ponga hielo en la espalda, el pecho o el trasero",
"Lamer el dedo del pie de alguien",
"Dejar que la persona que está a tu lado haga diez flexiones contigo debajo",
"Intercambiar calcetines con alguien del grupo",
"Dar una serenata a cualquiera del grupo",
"Encuentra una foto de una persona al azar en Internet y di cuánto significa para ti en una publicación en redes sociales",
"Tomar de la mano a uno de los otros jugadores durante el resto del juego",
"Comer espaguetis, al estilo de “La dama y el vagabundo”, con otro jugador",
"Dejar que uno de los jugadores te haga ‘calzón chino’",
"Pedirle a tu crush que salgan en una cita este fin de semana",
"Llamar por teléfono a los familiares de uno de tus amigos y cantar “Let It Go” de Frozen a todo pulmón",
"Fingir ser un perro orinando en un neumático",
"Inventar un rap en el acto y cantárselo a todos en la sala",
"Cada vez que uno de los otros jugadores elija “Reto”, camina por el suelo como un cangrejo",
"Ir a la casa de un vecino y explicarle que estás buscando a tu pingüino mascota, que resulta ser invisible",
"Durante los siguientes 5 minutos, habla con un profundo acento del campo",
"Haz un anillo con papel de aluminio y propónle matrimonio a quien esté sentado a tu derecha",
"Actuar de forma rara y oler el pelo de alguien hasta que se dé cuenta de lo que estás haciendo",
"Fingir que le quitas bichitos del pelo a alguien y te lo comes, como lo haría un mono",
"Permitir que alguien en la sala te haga un rápido y pequeño cambio de imagen",
"Hacer que uno de los otros jugadores repita algo al menos cinco veces fingiendo que no los oyes",
"Fingir ser una gallina que tiene problemas para poner un huevo",
"Llamar a uno de tus parientes y convencerlos de que realmente viste un OVNI",
"Llamar a tus padres y decirles que estás esperando un bebé",
"Hacer un sándwich con todos los condimentos de la nevera y comérselo",
"Dejar que uno de los otros jugadores te dibuje nuevas cejas con un marcador permanente",
"Enviar un mensaje a uno de tus amigos y decirle que no te gustó que se tirara pedos en tu presencia la última vez que salieron",
"Durante el resto del juego, finge hablar como el actual presidente de tu país",
"Llamar a una prostituta o a un club de striptease y preguntar por sus tarifas",
"Abrir cualquier libro al azar y leer toda la página como si estuvieras representando una obra de Shakespeare",
"Encontrar una peluca y cantar un verso y un coro de una canción de Whitney Houston",
"Masticar un chicle sin quitar el envoltorio",
"Quitarte los calcetines con los dientes",
"Lamer una pastilla de jabón que alguien acaba de usar",
"Llamar a un restaurante y hacer preguntas realmente estúpidas sobre una de sus opciones de menú",
"Hacer tu mejor imitación de Michael Jackson",
"Lleva una cinta que diga: “Bésame… es mi cumpleaños” en tu frente durante 0 minutos",
"Haz 20 flexiones y grita mi nombre con cada una",
"Exprime el jugo de un limón en tu codo y lámelo",
"Detén a la próxima persona que veas en el camino y dile “Te amo”",
"Canta en voz alta tu canción de amor favorita",
"Busca un lápiz de labios y póntelo",
"Aféitate el pecho",
"Dime algo que siempre quisiste decirme pero no pudiste",
"Ve a comprar un vestido nuevo conmigo",
"Envíame una captura de pantalla de tu historial de búsqueda de los últimos  días",
"Envía un mensaje romántico a alguien de tu mismo géner Envíame la respuesta",
"Tienes 20 minutos para escribir un poema corto de amor",
"Enumera a todas tus ex novias por orden alfabético",
"Escribe algo vergonzoso en algún lugar de tu cuerpo (que se pueda ocultar con la ropa) con un marcador permanente",
"Intenta bailar break dance durante 0 segundos",
"Haz flexiones de brazos hasta que no puedas hacer más, espera 5 segundos y luego haz una más",
"Gira un hula hoop imaginario alrededor de tu cintura durante 0 segundos",
"Baila durante  minuto “pole dance” con una barra imaginaria",
"Ve al baño, quítate la ropa interior y póntela en la cabeza",
"Come tu próxima comida en ropa interior",
"Ponte unos cubitos de hielo en tus pantalones y baila durante 20 segundos",
"Pela una papa o un plátano con los dientes",
"Escribe mi nombre en tu pecho y envíame la foto",
"Haz un baile sexy en una pierna",
"Quítate la camisa usando solo los dientes",
"Limpia tu habitación en ropa interior",
"Coge un libro al azar y léelo con la voz más seductora que puedas hacer",
"Liga conmigo como si estuviéramos en un bar",
"Cambia tu estado de Facebook a “se siente solo”",
"Envía a un amigo el mensaje más sucio que se te ocurra",
"Envíame la foto más poco favorecedora que tengas en tu teléfono",
"Envíame el último mensaje que le hayas enviado a tu madre",
"Envíame un video de ti comiendo un cuarto de taza de ketchup",
"Ponte todos los calzoncillos que tengas y envía una foto",
"Date una bofetada",
"Tienes un minuto para ponerte el traje más sexy que tengas",
"Dibuja un bigote en tu cara",
"Léeme el primer correo electrónico de tu bandeja de entrada",
 
]